
default: smoke

lint:
    python -m flake8 main.py

fmt:
    python -m black main.py

# run the script
smoke:
    #!/bin/sh
    source venv/bin/activate
    PY_LOG=debug python main.py

# debug run the script
debug:
    #!/bin/sh
    source venv/bin/activate
    . ./run-retry.sh

